In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

Nową kolumnę tworzy proste przypisanie do nieistniejącej jeszcze etykiety — `frame['TotalFat0'] = 0` albo z operacji na innych kolumnach: `frame['SugarAndFat'] = frame.Sugars + frame.TotalFat` — taka kolumna trafia zawsze na koniec DataFrame. Metoda `insert(loc=2, column=..., value=...)` pozwala wstawić nową kolumnę w wybranym miejscu zamiast na końcu. Kolumnę usuwa instrukcja `del frame['kolumna']`.

In [19]:
frame = pd.read_csv('/content/Mcdonalds.csv', usecols=['Item', 'Category', 'Calories', 'TotalFat', 'Sugars', 'Protein', 'Cholesterol'])
frame.head()

    Category                              Item  ...  Sugars  Protein
0  Breakfast                      Egg McMuffin  ...       3       17
1  Breakfast                 Egg White Delight  ...       3       18
2  Breakfast                  Sausage McMuffin  ...       2       14
3  Breakfast         Sausage McMuffin with Egg  ...       2       21
4  Breakfast  Sausage McMuffin with Egg Whites  ...       2       21

[5 rows x 7 columns]

Odwołanie do pojedyńczej kolumny

In [20]:
frame.TotalFat.head()

0    13.0
1     8.0
2    23.0
3    28.0
4    23.0
Name: TotalFat, dtype: float64

In [21]:
frame['TotalFat'].head()

0    13.0
1     8.0
2    23.0
3    28.0
4    23.0
Name: TotalFat, dtype: float64

Dodanie nowej kolumny

In [22]:
frame['TotalFat0'] = 0
frame.head()

    Category                              Item  ...  Protein  TotalFat0
0  Breakfast                      Egg McMuffin  ...       17          0
1  Breakfast                 Egg White Delight  ...       18          0
2  Breakfast                  Sausage McMuffin  ...       14          0
3  Breakfast         Sausage McMuffin with Egg  ...       21          0
4  Breakfast  Sausage McMuffin with Egg Whites  ...       21          0

[5 rows x 8 columns]

In [23]:
SugarAndFat = frame.Sugars + frame.TotalFat
frame['SugarAndFat'] = SugarAndFat
frame.head()

    Category                              Item  ...  TotalFat0  SugarAndFat
0  Breakfast                      Egg McMuffin  ...          0         16.0
1  Breakfast                 Egg White Delight  ...          0         11.0
2  Breakfast                  Sausage McMuffin  ...          0         25.0
3  Breakfast         Sausage McMuffin with Egg  ...          0         30.0
4  Breakfast  Sausage McMuffin with Egg Whites  ...          0         25.0

[5 rows x 9 columns]

In [24]:
SugarAndFat.head()

0    16.0
1    11.0
2    25.0
3    30.0
4    25.0
dtype: float64

Dodanie kolumny w jednej instrukcji

In [25]:
frame['SugarAndProtein'] = frame.Sugars + frame.Protein
frame.head()

    Category                              Item  ...  SugarAndFat  SugarAndProtein
0  Breakfast                      Egg McMuffin  ...         16.0               20
1  Breakfast                 Egg White Delight  ...         11.0               21
2  Breakfast                  Sausage McMuffin  ...         25.0               16
3  Breakfast         Sausage McMuffin with Egg  ...         30.0               23
4  Breakfast  Sausage McMuffin with Egg Whites  ...         25.0               23

[5 rows x 10 columns]

Nowe kolumny dochodzą na sam koniec, a co jeśli chcę umieścić kolumnę gdzieś w środku

In [26]:
frame.insert(loc=2, column='SPF', value=frame.Sugars+frame.Protein+frame.TotalFat)
frame.head()

    Category                              Item  ...  SugarAndFat  SugarAndProtein
0  Breakfast                      Egg McMuffin  ...         16.0               20
1  Breakfast                 Egg White Delight  ...         11.0               21
2  Breakfast                  Sausage McMuffin  ...         25.0               16
3  Breakfast         Sausage McMuffin with Egg  ...         30.0               23
4  Breakfast  Sausage McMuffin with Egg Whites  ...         25.0               23

[5 rows x 11 columns]

Usuwanie kolumn

In [27]:
del frame['SugarAndProtein']
frame.head()

    Category                              Item  ...  TotalFat0  SugarAndFat
0  Breakfast                      Egg McMuffin  ...          0         16.0
1  Breakfast                 Egg White Delight  ...          0         11.0
2  Breakfast                  Sausage McMuffin  ...          0         25.0
3  Breakfast         Sausage McMuffin with Egg  ...          0         30.0
4  Breakfast  Sausage McMuffin with Egg Whites  ...          0         25.0

[5 rows x 10 columns]