In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

Nazwy kolumn można nadpisać zbiorczo (`frame.columns = [...]`) albo zmienić wybrane etykiety — zarówno kolumn, jak i wartości indeksu — metodą `rename(columns={...})` / `rename(index={...})`. Ważna pułapka: `frameCopy = frame` nie tworzy kopii, tylko drugą referencję do tego samego obiektu w pamięci — zmiana w `frameCopy` zmienia też `frame`. Prawdziwą, niezależną kopię daje dopiero `frame.copy()`.

In [2]:
frame = pd.read_csv('/content/mammals.csv')
frame.head()

              name     body  brain
0       Arctic fox    3.385   44.5
1       Owl monkey    0.480   15.5
2  Mountain beaver    1.350    8.1
3              Cow  465.000  423.0
4        Grey wolf   36.330  119.5

In [3]:
frame.columns

Index(['name', 'body', 'brain'], dtype='object')

In [5]:
frame.columns = ['name', 'bodyKg', 'brainKg']
frame.head()

              name   bodyKg  brainKg
0       Arctic fox    3.385     44.5
1       Owl monkey    0.480     15.5
2  Mountain beaver    1.350      8.1
3              Cow  465.000    423.0
4        Grey wolf   36.330    119.5

Jeśli mam dużo kolumn stosuje słownik aby podmienić punktowo nazwy

In [12]:
newColumnNames = {'bodyKg':'body_kg','brainKg':'brain_kg'}
frame.rename(columns = newColumnNames, inplace=True)
frame.head()

              name  body_kg  brain_kg
0       Arctic fox    3.385      44.5
1       Owl monkey    0.480      15.5
2  Mountain beaver    1.350       8.1
3              Cow  465.000     423.0
4        Grey wolf   36.330     119.5

In [14]:
frame = pd.read_csv('/content/mammals.csv',index_col='name')
frame.head()

                    body  brain
name
Arctic fox         3.385   44.5
Owl monkey         0.480   15.5
Mountain beaver    1.350    8.1
Cow              465.000  423.0
Grey wolf         36.330  119.5

In [15]:
frame.rename(index = {'Cow':'Land cow'}, inplace=True)
frame.head()

                    body  brain
name
Arctic fox         3.385   44.5
Owl monkey         0.480   15.5
Mountain beaver    1.350    8.1
Land cow         465.000  423.0
Grey wolf         36.330  119.5

In [16]:
frameCopy = frame
frameCopy.head()

                    body  brain
name
Arctic fox         3.385   44.5
Owl monkey         0.480   15.5
Mountain beaver    1.350    8.1
Land cow         465.000  423.0
Grey wolf         36.330  119.5

In [17]:
frameCopy.loc['Arctic fox', 'body'] = 5
frameCopy.head()

                   body  brain
name
Arctic fox         5.00   44.5
Owl monkey         0.48   15.5
Mountain beaver    1.35    8.1
Land cow         465.00  423.0
Grey wolf         36.33  119.5

frameCopy - to tylko wskaźnik w pamięci do oryginalnego DataFrame

In [18]:
frame.head()

                   body  brain
name
Arctic fox         5.00   44.5
Owl monkey         0.48   15.5
Mountain beaver    1.35    8.1
Land cow         465.00  423.0
Grey wolf         36.33  119.5

Teraz kopiuje za pomocą copy()

In [20]:
frameCopy = frame.copy()
frameCopy.loc['Grey wolf', 'body'] = 40
frameCopy.head()

                   body  brain
name
Arctic fox         5.00   44.5
Owl monkey         0.48   15.5
Mountain beaver    1.35    8.1
Land cow         465.00  423.0
Grey wolf         40.00  119.5

In [21]:
frame.head()

                   body  brain
name
Arctic fox         5.00   44.5
Owl monkey         0.48   15.5
Mountain beaver    1.35    8.1
Land cow         465.00  423.0
Grey wolf         36.33  119.5