In [ ]:
import pandas as pd
import numpy as np

Budowa tabeli przestawnej: `df.pivot_table(index=..., columns=..., values=..., aggfunc=...)` tworzy tabelę z wielopoziomowym indeksem/kolumnami, którą można dalej porządkować metodami `swaplevel()` i `sort_index()`.

In [ ]:
sales = pd.read_csv('/content/WA_Sales_Products_2012-14.csv')
sales.head()

  Retailer country Order method type  ... Quantity Gross margin
0    United States               Fax  ...      489     0.347548
1    United States               Fax  ...      252     0.474274
2    United States               Fax  ...      147     0.352772
3    United States               Fax  ...      303     0.282938
4    United States               Fax  ...     1415     0.291450

[5 rows x 11 columns]

Pełna sygnatura `pivot_table()`: `values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All'` — domyślnym sposobem agregacji jest średnia (`aggfunc='mean'`), a `margins=True` dodaje wiersz/kolumnę z podsumowaniem.

In [ ]:
sales.pivot_table(index='Retailer country', columns=['Year','Quarter'],values='Revenue').head()

Year                      2012                ...          2014
Quarter                Q1 2012       Q2 2012  ...       Q2 2014       Q3 2014
Retailer country                              ...
Australia         18906.876142  16895.175467  ...  46304.001311  28287.220462
Austria           25401.670751  23912.953258  ...  41900.787028  23725.681168
Belgium           24773.419214  21039.834690  ...  33795.670882  20852.858542
Brazil            24750.126262  29493.933430  ...  42416.239016  25698.250601
Canada            32925.458510  31271.184460  ...  59625.791996  35206.803567

[5 rows x 11 columns]

In [ ]:
sales.pivot_table(index='Retailer country', columns=['Year'],values='Revenue').head()

Year                      2012          2013          2014
Retailer country
Australia         18264.652996  34738.181061  40465.826945
Austria           24072.485815  30630.862519  35320.573647
Belgium           22700.744951  25911.838406  31670.606449
Brazil            28107.451806  34711.962928  38342.489610
Canada            32610.629524  43712.280352  53718.102117

In [ ]:
sales.pivot_table(index='Retailer country', columns='Year', values='Gross margin', aggfunc='min').head()

Year                  2012      2013      2014
Retailer country
Australia        -0.389517  0.000766  0.000766
Austria           0.052200 -0.030436 -0.086616
Belgium          -1.476136  0.000766  0.000766
Brazil           -0.681869 -2.085496 -0.291963
Canada           -1.373907 -0.741547 -0.050334

In [ ]:
sales.pivot_table(index='Retailer country', columns='Year', values='Gross margin', aggfunc=['min', 'max']).head()

                       min                           max
Year                  2012      2013      2014      2012      2013      2014
Retailer country
Australia        -0.389517  0.000766  0.000766  0.770476  0.763231  0.757143
Austria           0.052200 -0.030436 -0.086616  0.770476  0.763231  0.759734
Belgium          -1.476136  0.000766  0.000766  0.770476  0.767760  0.759618
Brazil           -0.681869 -2.085496 -0.291963  0.770476  0.767760  0.758840
Canada           -1.373907 -0.741547 -0.050334  0.770476  0.767760  0.757660

In [7]:
pivTab = sales.pivot_table(index='Retailer country', columns='Year', values='Gross margin', aggfunc=['min', 'max'])
pivTab.columns

MultiIndex([('min', 2012),
            ('min', 2013),
            ('min', 2014),
            ('max', 2012),
            ('max', 2013),
            ('max', 2014)],
           names=[None, 'Year'])

In [11]:
pivTab = pivTab.swaplevel(axis='columns').sort_index(axis='columns').head()
pivTab.head()

Year                  2012                2013                2014
                       max       min       max       min       max       min
Retailer country
Australia         0.770476 -0.389517  0.763231  0.000766  0.757143  0.000766
Austria           0.770476  0.052200  0.763231 -0.030436  0.759734 -0.086616
Belgium           0.770476 -1.476136  0.767760  0.000766  0.759618  0.000766
Brazil            0.770476 -0.681869  0.767760 -2.085496  0.758840 -0.291963
Canada            0.770476 -1.373907  0.767760 -0.741547  0.757660 -0.050334