In [3]:
import pandas as pd
import numpy as np

Przykład operuje na strukturze przypominającej klasyczną bazę Northwind — kilka powiązanych tabel (Products, Orders, Customers, Employees, Categories, Suppliers itd.) połączonych kluczami obcymi. To typowy scenariusz łączenia danych: pojedyncza informacja (np. o produkcie) jest rozbita na kilka tabel, które trzeba scalić metodami `join()`/`merge()`, by uzyskać pełny obraz.

In [4]:
categories = pd.read_csv('/content/categories1.csv')
categories.head()

   CategoryID    CategoryName              Description
0           1       Beverages              Soft drinks
1           2      Condiments  Sweet and savory sauces
2           3     Confections                 Desserts
3           4  Dairy Products                  Cheeses
4           5  Grains/Cereals                   Breads

In [5]:
products = pd.read_csv('/content/products.csv')
products.head()

   ProductID                   ProductName  ...  ReorderLevel  Discontinued
0          1                          Chai  ...            10             0
1          2                         Chang  ...            25             0
2          3                 Aniseed Syrup  ...            25             0
3          4  Chef Anton's Cajun Seasoning  ...             0             0
4          5        Chef Anton's Gumbo Mix  ...             0             1

[5 rows x 10 columns]

In [6]:
supplires = pd.read_csv('/content/suppliers.csv')
supplires.head()

   SupplierID                         CompanyName  ...             Fax     HomePage
0           1                      Exotic Liquids  ...             NaN          NaN
1           2          New Orleans Cajun Delights  ...             NaN  #CAJUN.HTM#
2           3           Grandma Kelly's Homestead  ...  (313) 555-3349          NaN
3           4                       Tokyo Traders  ...             NaN          NaN
4           5  Cooperativa de Quesos 'Las Cabras'  ...             NaN          NaN

[5 rows x 12 columns]

In [7]:
customers = pd.read_csv('/content/customers.csv')
customers.head()

  CustomerID  ...             Fax
0      ALFKI  ...     030-0076545
1      ANATR  ...    (5) 555-3745
2      ANTON  ...             NaN
3      AROUT  ...  (171) 555-6750
4      BERGS  ...   0921-12 34 67

[5 rows x 11 columns]

##append i concat

Metoda `append()` (usunięta w nowszych wersjach pandas na rzecz `pd.concat()`) oraz `pd.concat([df1, df2, ...])` sklejają DataFrame'y jeden pod drugim. Parametr `ignore_index=True` nadaje wynikowi nowy, ciągły indeks zamiast zachowywać oryginalne indeksy obu ramek.

In [10]:
suppliers = pd.read_csv('/content/suppliers.csv', usecols = ['SupplierID', 'CompanyName', 'Country'])
suppliers.head()

   SupplierID                         CompanyName Country
0           1                      Exotic Liquids      UK
1           2          New Orleans Cajun Delights     USA
2           3           Grandma Kelly's Homestead     USA
3           4                       Tokyo Traders   Japan
4           5  Cooperativa de Quesos 'Las Cabras'   Spain

In [11]:
customers = pd.read_csv('/content/customers.csv', usecols=['CustomerID', 'CompanyName', 'Country'])
customers.head()

  CustomerID                         CompanyName  Country
0      ALFKI                 Alfreds Futterkiste  Germany
1      ANATR  Ana Trujillo Emparedados y helados   Mexico
2      ANTON            Antonio Moreno Taquer?­a   Mexico
3      AROUT                     Around the Horn       UK
4      BERGS                 Berglunds snabbk?¶p   Sweden

In [12]:
len(supplires)

29

In [13]:
len(customers)

91

In [14]:
suppliers.append(customers)

    SupplierID                         CompanyName  Country CustomerID
0          1.0                      Exotic Liquids       UK        NaN
1          2.0          New Orleans Cajun Delights      USA        NaN
2          3.0           Grandma Kelly's Homestead      USA        NaN
3          4.0                       Tokyo Traders    Japan        NaN
4          5.0  Cooperativa de Quesos 'Las Cabras'    Spain        NaN
..         ...                                 ...      ...        ...
86         NaN                      Wartian Herkku  Finland      WARTH
87         NaN              Wellington Importadora   Brazil      WELLI
88         NaN                White Clover Markets      USA      WHITC
89         NaN                         Wilman Kala  Finland      WILMK
90         NaN                      Wolski  Zajazd   Poland      WOLZA

[120 rows x 4 columns]

In [15]:
df_append = suppliers.append(customers)
len(df_append)

120

In [16]:
suppliers2 = suppliers.copy()
customers2 = customers.copy()

In [18]:
suppliers2.rename({ 'SupplierID' : 'CustomerID'}, axis='columns', inplace=True)

In [19]:
suppliers2.head()

   CustomerID                         CompanyName Country
0           1                      Exotic Liquids      UK
1           2          New Orleans Cajun Delights     USA
2           3           Grandma Kelly's Homestead     USA
3           4                       Tokyo Traders   Japan
4           5  Cooperativa de Quesos 'Las Cabras'   Spain

In [20]:
suppliers2.append(customers)

   CustomerID                         CompanyName  Country
0           1                      Exotic Liquids       UK
1           2          New Orleans Cajun Delights      USA
2           3           Grandma Kelly's Homestead      USA
3           4                       Tokyo Traders    Japan
4           5  Cooperativa de Quesos 'Las Cabras'    Spain
..        ...                                 ...      ...
86      WARTH                      Wartian Herkku  Finland
87      WELLI              Wellington Importadora   Brazil
88      WHITC                White Clover Markets      USA
89      WILMK                         Wilman Kala  Finland
90      WOLZA                      Wolski  Zajazd   Poland

[120 rows x 3 columns]

In [21]:
df_concat = pd.concat(objs=[suppliers2,customers])
len(df_concat)

120

In [45]:
df_concat.head(5)

  CustomerID                         CompanyName Country
0          1                      Exotic Liquids      UK
1          2          New Orleans Cajun Delights     USA
2          3           Grandma Kelly's Homestead     USA
3          4                       Tokyo Traders   Japan
4          5  Cooperativa de Quesos 'Las Cabras'   Spain

##Join()

Metoda `df1.join(df2, on='col1')` łączy dwa DataFrame domyślnie po ich indeksach — jeśli `col1` nie jest jeszcze indeksem, trzeba go najpierw ustawić metodą `set_index()`.

In [23]:
prod_1 = pd.read_csv('/content/products.csv', usecols=['ProductID', 'ProductName'],index_col='ProductID')
prod_2 = pd.read_csv('/content/products.csv', usecols=['ProductID', 'UnitPrice'],index_col='ProductID')

In [24]:
prod_1.head()

                            ProductName
ProductID
1                                  Chai
2                                 Chang
3                         Aniseed Syrup
4          Chef Anton's Cajun Seasoning
5                Chef Anton's Gumbo Mix

In [25]:
prod_2.head()

           UnitPrice
ProductID
1              18.00
2              19.00
3              10.00
4              22.00
5              21.35

In [26]:
prod_1.join(prod_2).head()

                            ProductName  UnitPrice
ProductID
1                                  Chai      18.00
2                                 Chang      19.00
3                         Aniseed Syrup      10.00
4          Chef Anton's Cajun Seasoning      22.00
5                Chef Anton's Gumbo Mix      21.35

In [27]:
categories = pd.read_csv('/content/categories1.csv', usecols = ['CategoryID', 'CategoryName', 'Description'])
categories.head()

   CategoryID    CategoryName              Description
0           1       Beverages              Soft drinks
1           2      Condiments  Sweet and savory sauces
2           3     Confections                 Desserts
3           4  Dairy Products                  Cheeses
4           5  Grains/Cereals                   Breads

In [28]:
products = pd.read_csv('/content/products.csv', usecols= ['ProductID', 'ProductName', 'UnitPrice', 'CategoryID'])
products.head()

   ProductID                   ProductName  CategoryID  UnitPrice
0          1                          Chai           1      18.00
1          2                         Chang           1      19.00
2          3                 Aniseed Syrup           2      10.00
3          4  Chef Anton's Cajun Seasoning           2      22.00
4          5        Chef Anton's Gumbo Mix           2      21.35

In [29]:
categories.set_index('CategoryID', inplace=True)
categories.head()

              CategoryName              Description
CategoryID
1                Beverages              Soft drinks
2               Condiments  Sweet and savory sauces
3              Confections                 Desserts
4           Dairy Products                  Cheeses
5           Grains/Cereals                   Breads

In [30]:
products.join(other=categories, on = 'CategoryID')

    ProductID  ...                Description
0           1  ...                Soft drinks
1           2  ...                Soft drinks
2           3  ...    Sweet and savory sauces
3           4  ...    Sweet and savory sauces
4           5  ...    Sweet and savory sauces
..        ...  ...                        ...
72         73  ...           Seaweed and fish
73         74  ...  Dried fruit and bean curd
74         75  ...                Soft drinks
75         76  ...                Soft drinks
76         77  ...    Sweet and savory sauces

[77 rows x 6 columns]

##Merge()

Metoda `merge()` łączy dwa DataFrame po wspólnej kolumnie lub indeksie, z pełną kontrolą nad sposobem łączenia przez parametr `how`: `"inner"` zostawia tylko wiersze wspólne dla obu tabel, `"left"`/`"right"` zachowują wszystkie wiersze z jednej strony (dopełniając brakujące dane wartością `NaN`), a `"outer"` zachowuje wiersze z obu tabel niezależnie od dopasowania.

In [ ]:
cat1 = pd.read_csv('/content/categories_del_1.csv', usecols = ['CategoryID', 'CategoryName'])
cat2 = pd.read_csv('/content/categories_del_2.csv', usecols = ['CategoryID', 'CategoryName'])

In [ ]:
cat1

   CategoryID    CategoryName
0           2      Condiments
1           3     Confections
2           4  Dairy Products
3           5  Grains/Cereals
4           6    Meat/Poultry
5           7         Produce
6           8         Seafood

In [ ]:
cat2

   CategoryID    CategoryName
0           1       Beverages
1           2      Condiments
2           3     Confections
3           4  Dairy Products
4           7         Produce
5           8         Seafood

In [ ]:
cat1.merge(cat2)

   CategoryID    CategoryName
0           2      Condiments
1           3     Confections
2           4  Dairy Products
3           7         Produce
4           8         Seafood

In [ ]:
cat1.merge(cat2, on='CategoryID')

   CategoryID  CategoryName_x  CategoryName_y
0           2      Condiments      Condiments
1           3     Confections     Confections
2           4  Dairy Products  Dairy Products
3           7         Produce         Produce
4           8         Seafood         Seafood

In [ ]:
cat1.merge(cat2, on='CategoryID', suffixes=['_1','_2'])

   CategoryID  CategoryName_1  CategoryName_2
0           2      Condiments      Condiments
1           3     Confections     Confections
2           4  Dairy Products  Dairy Products
3           7         Produce         Produce
4           8         Seafood         Seafood

In [ ]:
cat1.merge(cat2,on='CategoryID', suffixes=['_1','_2'],how='outer')

   CategoryID  CategoryName_1  CategoryName_2
0           2      Condiments      Condiments
1           3     Confections     Confections
2           4  Dairy Products  Dairy Products
3           5  Grains/Cereals             NaN
4           6    Meat/Poultry             NaN
5           7         Produce         Produce
6           8         Seafood         Seafood
7           1             NaN       Beverages

In [ ]:
cat1.merge(cat2,on='CategoryID', suffixes=['_1','_2'],how='outer',indicator=True)

   CategoryID  CategoryName_1  CategoryName_2      _merge
0           2      Condiments      Condiments        both
1           3     Confections     Confections        both
2           4  Dairy Products  Dairy Products        both
3           5  Grains/Cereals             NaN   left_only
4           6    Meat/Poultry             NaN   left_only
5           7         Produce         Produce        both
6           8         Seafood         Seafood        both
7           1             NaN       Beverages  right_only

In [ ]:
cat_merged = cat1.merge(cat2,on='CategoryID', suffixes=['_1','_2'],how='outer',indicator=True)

In [ ]:
cat_merged['_merge'] == 'left_only'

0    False
1    False
2    False
3     True
4     True
5    False
6    False
7    False
Name: _merge, dtype: bool

In [ ]:
filter = cat_merged['_merge'] == 'left_only'
cat_merged[filter]

   CategoryID  CategoryName_1 CategoryName_2     _merge
3           5  Grains/Cereals            NaN  left_only
4           6    Meat/Poultry            NaN  left_only

In [ ]:
filter = cat_merged['_merge'] == 'right_only'
cat_merged[filter]

   CategoryID CategoryName_1 CategoryName_2      _merge
7           1            NaN      Beverages  right_only

In [ ]:
filter = cat_merged['_merge'] == 'both'
cat_merged[filter]

   CategoryID  CategoryName_1  CategoryName_2 _merge
0           2      Condiments      Condiments   both
1           3     Confections     Confections   both
2           4  Dairy Products  Dairy Products   both
5           7         Produce         Produce   both
6           8         Seafood         Seafood   both

In [ ]:
cat1.merge(cat2,on='CategoryID', suffixes=['_1','_2'],how='left',indicator=True)

   CategoryID  CategoryName_1  CategoryName_2     _merge
0           2      Condiments      Condiments       both
1           3     Confections     Confections       both
2           4  Dairy Products  Dairy Products       both
3           5  Grains/Cereals             NaN  left_only
4           6    Meat/Poultry             NaN  left_only
5           7         Produce         Produce       both
6           8         Seafood         Seafood       both

In [ ]:
cat1.merge(cat2,on='CategoryID', suffixes=['_1','_2'],how='right',indicator=True)

   CategoryID  CategoryName_1  CategoryName_2      _merge
0           1             NaN       Beverages  right_only
1           2      Condiments      Condiments        both
2           3     Confections     Confections        both
3           4  Dairy Products  Dairy Products        both
4           7         Produce         Produce        both
5           8         Seafood         Seafood        both

## Outer merge

In [32]:
products = pd.read_csv('/content/products.csv', usecols = ['ProductID', 'ProductName'])

orderedProducts = pd.read_csv('/content/order-details_del.csv', 
                              usecols = ['OrderID','ProductID', 'UnitPrice', 'Quantity'])

In [33]:
products.head()

   ProductID                   ProductName
0          1                          Chai
1          2                         Chang
2          3                 Aniseed Syrup
3          4  Chef Anton's Cajun Seasoning
4          5        Chef Anton's Gumbo Mix

In [34]:
orderedProducts.head()

   OrderID  ProductID  UnitPrice  Quantity
0    10331         54        5.9        15
1    10332         18       50.0        40
2    10332         42       11.2        10
3    10332         47        7.6        16
4    10333         14       18.6        10

Wyświetlenie produktów, które się nie sprzedały

In [35]:
merged = products.merge(right=orderedProducts, on='ProductID', how='outer', indicator=True)
merged.head()

   ProductID ProductName  OrderID  UnitPrice  Quantity _merge
0          1        Chai  10348.0       14.4      15.0   both
1          1        Chai  10354.0       14.4      12.0   both
2          1        Chai  10370.0       14.4      15.0   both
3          1        Chai  10406.0       14.4      10.0   both
4          1        Chai  10413.0       14.4      24.0   both

In [36]:
merged = orderedProducts.merge(right=products, on='ProductID', how='outer', indicator=True)
merged.head()

   OrderID  ProductID  UnitPrice  Quantity ProductName _merge
0  10331.0         54        5.9      15.0   Tourtière   both
1  10349.0         54        5.9      24.0   Tourtière   both
2  10352.0         54        5.9      20.0   Tourtière   both
3  10360.0         54        5.9      28.0   Tourtière   both
4  10362.0         54        5.9      24.0   Tourtière   both

In [37]:
merged['_merge'].value_counts()

both          289
right_only      5
left_only       0
Name: _merge, dtype: int64

In [38]:
filter = merged['_merge'] == 'right_only'
merged[filter]

     OrderID  ProductID  ...                   ProductName      _merge
289      NaN          6  ...  Grandma's Boysenberry Spread  right_only
290      NaN         15  ...                  Genen Shouyu  right_only
291      NaN         27  ...            Schoggi Schokolade  right_only
292      NaN         66  ...     Louisiana Hot Spiced Okra  right_only
293      NaN         67  ...     Laughing Lumberjack Lager  right_only

[5 rows x 6 columns]

##Left & right merge

In [39]:
products.head()

   ProductID                   ProductName
0          1                          Chai
1          2                         Chang
2          3                 Aniseed Syrup
3          4  Chef Anton's Cajun Seasoning
4          5        Chef Anton's Gumbo Mix

In [40]:
orderedProducts.head()

   OrderID  ProductID  UnitPrice  Quantity
0    10331         54        5.9        15
1    10332         18       50.0        40
2    10332         42       11.2        10
3    10332         47        7.6        16
4    10333         14       18.6        10

In [41]:
mergedLeft = products.merge(right=orderedProducts, on='ProductID', how='left', indicator=True)
mergedLeft.head()

   ProductID ProductName  OrderID  UnitPrice  Quantity _merge
0          1        Chai  10348.0       14.4      15.0   both
1          1        Chai  10354.0       14.4      12.0   both
2          1        Chai  10370.0       14.4      15.0   both
3          1        Chai  10406.0       14.4      10.0   both
4          1        Chai  10413.0       14.4      24.0   both

In [42]:
mergedLeft['_merge'].value_counts()

both          289
left_only       5
right_only      0
Name: _merge, dtype: int64

In [43]:
mergedRight = products.merge(right=orderedProducts, on='ProductID', how='right', indicator=True)
mergedRight.head()

   ProductID ProductName  OrderID  UnitPrice  Quantity _merge
0         54   Tourtière    10331        5.9        15   both
1         54   Tourtière    10349        5.9        24   both
2         54   Tourtière    10352        5.9        20   both
3         54   Tourtière    10360        5.9        28   both
4         54   Tourtière    10362        5.9        24   both

In [44]:
mergedRight['_merge'].value_counts()

both          289
right_only      0
left_only       0
Name: _merge, dtype: int64

##Opcje polecenia merge

Najważniejsze opcje `merge()`: `left_on`/`right_on` pozwalają łączyć po kolumnach o różnych nazwach w obu tabelach, `left_index`/`right_index` łączą po indeksie zamiast kolumny, `suffixes` rozstrzyga konflikt nazw kolumn występujących w obu ramkach, a `sort=True` sortuje wynik po kluczu łączenia.

In [ ]:
products = pd.read_csv('/content/products.csv', usecols = ['ProductID', 'ProductName', 'CategoryID', 'UnitPrice'])

categories = pd.read_csv('/content/categories1.csv', 
                              usecols = ['CategoryID', 'CategoryName', 'Description'])

In [ ]:
products.head()

   ProductID                   ProductName  CategoryID  UnitPrice
0          1                          Chai           1      18.00
1          2                         Chang           1      19.00
2          3                 Aniseed Syrup           2      10.00
3          4  Chef Anton's Cajun Seasoning           2      22.00
4          5        Chef Anton's Gumbo Mix           2      21.35

In [ ]:
categories.head()

   CategoryID    CategoryName              Description
0           1       Beverages              Soft drinks
1           2      Condiments  Sweet and savory sauces
2           3     Confections                 Desserts
3           4  Dairy Products                  Cheeses
4           5  Grains/Cereals                   Breads

In [ ]:
products.merge(right=categories, on='CategoryID').head()

   ProductID         ProductName  ...  CategoryName  Description
0          1                Chai  ...     Beverages  Soft drinks
1          2               Chang  ...     Beverages  Soft drinks
2         24  Guaraná Fantástica  ...     Beverages  Soft drinks
3         34       Sasquatch Ale  ...     Beverages  Soft drinks
4         35      Steeleye Stout  ...     Beverages  Soft drinks

[5 rows x 6 columns]

In [ ]:
categories.rename({'CategoryID' : 'ID'}, axis='columns', inplace=True)
categories.head()

   ID    CategoryName              Description
0   1       Beverages              Soft drinks
1   2      Condiments  Sweet and savory sauces
2   3     Confections                 Desserts
3   4  Dairy Products                  Cheeses
4   5  Grains/Cereals                   Breads

In [ ]:
products.merge(right=categories, left_on='CategoryID', right_on='ID').head()

   ProductID         ProductName  CategoryID  ...  ID  CategoryName  Description
0          1                Chai           1  ...   1     Beverages  Soft drinks
1          2               Chang           1  ...   1     Beverages  Soft drinks
2         24  Guaraná Fantástica           1  ...   1     Beverages  Soft drinks
3         34       Sasquatch Ale           1  ...   1     Beverages  Soft drinks
4         35      Steeleye Stout           1  ...   1     Beverages  Soft drinks

[5 rows x 7 columns]

In [ ]:
products.rename({'ProductName' : 'Name'}, axis='columns', inplace=True)

In [ ]:
categories.rename({'CategoryName' : 'Name'}, axis='columns', inplace=True)

In [ ]:
products.head(3)

   ProductID           Name  CategoryID  UnitPrice
0          1           Chai           1       18.0
1          2          Chang           1       19.0
2          3  Aniseed Syrup           2       10.0

In [ ]:
categories.head(3)

   ID         Name              Description
0   1    Beverages              Soft drinks
1   2   Condiments  Sweet and savory sauces
2   3  Confections                 Desserts

In [ ]:
products.merge(right=categories, left_on='CategoryID', right_on='ID').head()

   ProductID              Name_x  CategoryID  ...  ID     Name_y  Description
0          1                Chai           1  ...   1  Beverages  Soft drinks
1          2               Chang           1  ...   1  Beverages  Soft drinks
2         24  Guaraná Fantástica           1  ...   1  Beverages  Soft drinks
3         34       Sasquatch Ale           1  ...   1  Beverages  Soft drinks
4         35      Steeleye Stout           1  ...   1  Beverages  Soft drinks

[5 rows x 7 columns]

In [ ]:
products.merge(right=categories, left_on='CategoryID', right_on='ID', suffixes=['_prod', '_category']).head()

   ProductID           Name_prod  CategoryID  ...  ID  Name_category  Description
0          1                Chai           1  ...   1      Beverages  Soft drinks
1          2               Chang           1  ...   1      Beverages  Soft drinks
2         24  Guaraná Fantástica           1  ...   1      Beverages  Soft drinks
3         34       Sasquatch Ale           1  ...   1      Beverages  Soft drinks
4         35      Steeleye Stout           1  ...   1      Beverages  Soft drinks

[5 rows x 7 columns]

In [ ]:
products.merge(right=categories, left_on='CategoryID', right_on='ID', suffixes=['_prod', '_category'],
               sort=True).head()

   ProductID           Name_prod  CategoryID  ...  ID  Name_category  Description
0          1                Chai           1  ...   1      Beverages  Soft drinks
1          2               Chang           1  ...   1      Beverages  Soft drinks
2         24  Guaraná Fantástica           1  ...   1      Beverages  Soft drinks
3         34       Sasquatch Ale           1  ...   1      Beverages  Soft drinks
4         35      Steeleye Stout           1  ...   1      Beverages  Soft drinks

[5 rows x 7 columns]

In [ ]:
categories.head()

   ID            Name              Description
0   1       Beverages              Soft drinks
1   2      Condiments  Sweet and savory sauces
2   3     Confections                 Desserts
3   4  Dairy Products                  Cheeses
4   5  Grains/Cereals                   Breads

In [ ]:
categories.set_index('ID', inplace=True)
categories.head()

              Name              Description
ID
1        Beverages              Soft drinks
2       Condiments  Sweet and savory sauces
3      Confections                 Desserts
4   Dairy Products                  Cheeses
5   Grains/Cereals                   Breads

In [ ]:
products.merge(right=categories, left_on='CategoryID', right_index=True, suffixes=['_prod', '_category'],
               sort=True).head()

    ProductID           Name_prod  ...  Name_category  Description
0           1                Chai  ...      Beverages  Soft drinks
1           2               Chang  ...      Beverages  Soft drinks
23         24  Guaraná Fantástica  ...      Beverages  Soft drinks
33         34       Sasquatch Ale  ...      Beverages  Soft drinks
34         35      Steeleye Stout  ...      Beverages  Soft drinks

[5 rows x 6 columns]

##Łączenie 3 i więcej Data Frame

Łańcuch wywołań `df1.merge(df2, ...).merge(df3, ...)` pozwala połączyć więcej niż dwie tabele w jednym wyrażeniu — każde kolejne `merge()` działa na wyniku poprzedniego. Warto ustawiać `suffixes` przy każdym łączeniu osobno, żeby uniknąć niejednoznacznych nazw kolumn w wyniku końcowym.

In [ ]:
products = pd.read_csv('/content/products.csv', usecols = ['ProductID', 'ProductName', 'CategoryID', 'UnitPrice'])

categories = pd.read_csv('/content/categories1.csv', usecols = ['CategoryID', 'CategoryName', 'Description'])

orders = pd.read_csv('/content/order-details.csv')

In [ ]:
products.head(2)

   ProductID ProductName  CategoryID  UnitPrice
0          1        Chai           1       18.0
1          2       Chang           1       19.0

In [ ]:
categories.head(2)

   CategoryID CategoryName              Description
0           1    Beverages              Soft drinks
1           2   Condiments  Sweet and savory sauces

In [ ]:
orders.head(2)

   OrderID  ProductID  UnitPrice  Quantity  Discount
0    10248         11       14.0        12       0.0
1    10248         42        9.8        10       0.0

In [ ]:
cat_prod = products.merge(categories, on='CategoryID')
cat_prod.head(2)

   ProductID ProductName  CategoryID  UnitPrice CategoryName  Description
0          1        Chai           1       18.0    Beverages  Soft drinks
1          2       Chang           1       19.0    Beverages  Soft drinks

In [ ]:
cat_prod.merge(orders, on='ProductID').head()

   ProductID ProductName  CategoryID  ...  UnitPrice_y Quantity Discount
0          1        Chai           1  ...         14.4       45     0.20
1          1        Chai           1  ...         14.4       18     0.00
2          1        Chai           1  ...         14.4       20     0.00
3          1        Chai           1  ...         14.4       15     0.15
4          1        Chai           1  ...         14.4       12     0.00

[5 rows x 10 columns]

In [ ]:
cat_prod.merge(orders, on='ProductID', suffixes=['_Prod', '_Order']).head()

   ProductID ProductName  CategoryID  ...  UnitPrice_Order Quantity Discount
0          1        Chai           1  ...             14.4       45     0.20
1          1        Chai           1  ...             14.4       18     0.00
2          1        Chai           1  ...             14.4       20     0.00
3          1        Chai           1  ...             14.4       15     0.15
4          1        Chai           1  ...             14.4       12     0.00

[5 rows x 10 columns]